"""
File: opsProject.py
Description: Project Management UI and backend logic for openPypeline Studio.
             Handles creating, editing, removing projects, and user management.
             Refactored from openPipelineProject.mel to Python 3.
             
Original Framework: openPipeline by Kickstand
License: Common Public License 1.0 (CPL-1.0)
"""

import os
import re
import logging
from openpypeline.core.util import prefs
from PySide6 import QtWidgets, QtCore

import opsInfo
import opsUtils
import opsActions

logger = logging.getLogger("openPypeline.project")


def get_proj_file():
    """Returns the full path of the Project configuration file."""
    proj_path = prefs.get_pref("ops_projectFilePath", "")
    if not proj_path or str(proj_path).strip() in ["", "Not Set"]:
        return ""
    return os.path.join(proj_path, "openPipeline_projects.xml").replace("\\", "/")


def get_projects_data():
    """Returns the full data of all existing projects as a list of XML strings."""
    proj_file = get_proj_file()
    if not proj_file:
        return []
    if os.path.isfile(proj_file):
        try:
            with open(proj_file, 'r', encoding="utf-8") as f:
                content = f.read()
            projects = re.findall(r'<project>(.*?)</project>', content, re.DOTALL)
            return [f"<project>{p}</project>" for p in projects]
        except Exception:
            pass
    else:
        proj_dir = os.path.dirname(proj_file)
        if proj_dir:
            try:
                os.makedirs(proj_dir, exist_ok=True)
                with open(proj_file, 'w', encoding="utf-8") as f:
                    f.write("<!--This file is automatically generated by openPypeline. Edit at your own risk!-->\n")
                    f.write("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n")
                    f.write("<openPipeline_project_list>\n</openPipeline_project_list>\n")
            except Exception as e:
                logger.error(f"Project File does not exist, could not be opened, or could not be created: {e}")
    return []


def get_single_project_xml(proj_name):
    """Returns the data for a single project in XML."""
    proj_data = get_projects_data()
    for p in proj_data:
        if opsUtils.get_xml_data(p, "name") == proj_name:
            return p
    return ""


def rewrite_proj_file(proj_list):
    """Rewrites the project xml file with the data it is passed as a string array."""
    proj_file = get_proj_file()
    if not proj_file:
        logger.error("Project file path is not set. Please use 'Edit Locations...' to set it.")
        return
    try:
        with open(proj_file, 'w', encoding="utf-8") as f:
            f.write("<!--This file is automatically generated by openPypeline. Edit at your own risk!-->\n")
            f.write("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n")
            f.write("<?xml-stylesheet type=\"text/xsl\" href=\"xsl/plStylesheet.xsl\"?>\n")
            f.write("<openPipeline_project_list>\n")
            for proj in proj_list:
                p_content = proj.replace("<project>", "").replace("</project>", "").strip()
                f.write(f"    <project>\n        {p_content}\n    </project>\n")
            f.write("</openPipeline_project_list>\n")
    except Exception as e:
        logger.error(f"Project File {proj_file} could not be found, or is not writable: {e}")


def close_proj_ui(*args):
    """Legacy hook for closing Project UIs. Now handled natively by PySide."""
    pass


def get_project_info_string(proj_name):
    """Returns a formatted string containing project details for the UI."""
    proj_xml = get_single_project_xml(proj_name)
    if not proj_xml: return ""
    
    status_str = ["inactive", "active"][int(opsUtils.get_xml_data(proj_xml, "status") or 1)]
    
    info = (
        f"Project Name: {opsUtils.get_xml_data(proj_xml, 'name')}\n"
        f"Path: {opsUtils.get_xml_data(proj_xml, 'path')}\n"
        f"Description: {opsUtils.get_xml_data(proj_xml, 'description')}\n"
        f"Status: {status_str}\n"
        f"-------------------------------------\n"
        f"Date Created: {opsUtils.get_xml_data(proj_xml, 'date')}\n"
        f"Deadline: {opsUtils.get_xml_data(proj_xml, 'deadline')}\n"
        f"-------------------------------------\n"
        f"Master Files:\nname - {opsUtils.get_xml_data(proj_xml, 'mastername')}\nformat - {opsUtils.get_xml_data(proj_xml, 'masterformat')}\n"
        f"Workshop Files:\nname - {opsUtils.get_xml_data(proj_xml, 'wipname')}\nformat - {opsUtils.get_xml_data(proj_xml, 'wipformat')}\n"
        f"-------------------------------------\n"
        f"Library Sub-folder:    {opsUtils.get_xml_data(proj_xml, 'libraryfolder')}\n"
        f"Shots Sub-folder:      {opsUtils.get_xml_data(proj_xml, 'scenesfolder')}\n"
        f"Scripts Sub-folder:    {opsUtils.get_xml_data(proj_xml, 'scriptsfolder')}\n"
        f"Renders Sub-folder:    {opsUtils.get_xml_data(proj_xml, 'rendersfolder')}\n"
        f"Textures Sub-folder:   {opsUtils.get_xml_data(proj_xml, 'texturesfolder')}\n"
        f"Particles Sub-folder:  {opsUtils.get_xml_data(proj_xml, 'particlesfolder')}\n"
        f"Archive folder:        {opsUtils.get_xml_data(proj_xml, 'archivefolder')}\n"
        f"Deleted Items folder:  {opsUtils.get_xml_data(proj_xml, 'deletedfolder')}\n"
        f"Users:  {opsUtils.get_xml_data(proj_xml, 'users')}\n"
    )
    
    return info


def get_users():
    """Reads the users.xml file."""
    proj_path = prefs.get_pref("ops_projectFilePath", "")
    if not proj_path or str(proj_path).strip() in ["", "Not Set"]:
        return []
    users_file = os.path.join(proj_path, "openPipeline_users.xml").replace("\\", "/")
    if os.path.isfile(users_file):
        with open(users_file, "r") as f:
            return [line.strip() for line in f if line.strip()]
    return []


def edit_users_save_file(users):
    """Updates user.xml file with users, overwrites existing."""
    proj_path = prefs.get_pref("ops_projectFilePath", "")
    if not proj_path or str(proj_path).strip() in ["", "Not Set"]:
        logger.warning("Project file path is not set. Cannot save users.")
        return
    users_file = os.path.join(proj_path, "openPipeline_users.xml").replace("\\", "/")
    with open(users_file, "w") as f:
        for user in users:
            f.write(f"{user}\n")


class EditUsersDialog(QtWidgets.QDialog):
    """PySide6 Dialog for adding and removing global project users."""
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setWindowTitle("Add / Remove Users")
        self.setMinimumSize(340, 230)
        
        layout = QtWidgets.QVBoxLayout(self)
        
        self.user_list = QtWidgets.QListWidget()
        self.user_list.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self._refresh_list()
        layout.addWidget(self.user_list)
        
        btn_layout = QtWidgets.QHBoxLayout()
        self.add_btn = QtWidgets.QPushButton("Add user")
        self.remove_btn = QtWidgets.QPushButton("Remove Selected")
        self.close_btn = QtWidgets.QPushButton("Close")
        
        self.add_btn.clicked.connect(self.on_add)
        self.remove_btn.clicked.connect(self.on_remove)
        self.close_btn.clicked.connect(self.accept)
        
        btn_layout.addWidget(self.add_btn)
        btn_layout.addWidget(self.remove_btn)
        btn_layout.addWidget(self.close_btn)
        layout.addLayout(btn_layout)
        
    def _refresh_list(self):
        self.user_list.clear()
        self.user_list.addItems(get_users())
        
    def on_add(self):
        name, ok = QtWidgets.QInputDialog.getText(self, "Add User", "Enter Name:")
        if ok and name.strip():
            users = get_users()
            if name.strip() not in users:
                users.append(name.strip())
                edit_users_save_file(users)
                self._refresh_list()
                
    def on_remove(self):
        selected = [item.text() for item in self.user_list.selectedItems()]
        if not selected: return
        
        users = get_users()
        users = [u for u in users if u not in selected]
        edit_users_save_file(users)
        self._refresh_list()


def proj_edit_users(*args):
    """Launches the PySide6 UI to edit global project users."""
    dialog = EditUsersDialog()
    dialog.exec()